POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"dklsfjkjdfsl",
    "number":"123456"
}

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"dklsfjkjdfsl",
    "number":"12345689"
}
###